"""update

Revision ID: 5a5cf340e2fe
Revises: be53a15e9cd3
Create Date: 2024-06-05 14:57:19.773779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5cf340e2fe'
down_revision: Union[str, None] = 'be53a15e9cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('category_created_by_id_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.drop_column('category', 'created_by_id')
    op.add_column('todo', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('todo', sa.Column('category_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('todo_categoty_id_fkey', 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['id'])
    op.drop_column('todo', 'categoty_id')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.alter_column('user', 'hashed_password',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)
    op.add_column('todo', sa.Column('categoty_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key('todo_categoty_id_fkey', 'todo', 'category', ['categoty_id'], ['id'])
    op.drop_column('todo', 'category_id')
    op.drop_column('todo', 'is_completed')
    op.add_column('category', sa.Column('created_by_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_created_by_id_fkey', 'category', 'user', ['created_by_id'], ['id'])
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###
